// universities.ts

const universities: string[] = [
"University of Aberdeen",
"Abertay University",
"Aberystwyth University",
"Anglia Ruskin University",
"Arden University",
"Aston University",
"Bangor University",
"University of Bath",
"Bath Spa University",
"University of Bedfordshire",
"BIMM University",
"University of Birmingham",
"Birmingham City University",
"University College Birmingham",
"Bishop Grosseteste University",
"University of Bolton",
"Arts University Bournemouth",
"Bournemouth University",
"BPP University",
"University of Bradford",
"University of Brighton",
"University of Bristol",
"Brunel University London",
"University of Buckingham",
"Buckinghamshire New University",
"University of Cambridge",
"Canterbury Christ Church University",
"Cardiff Metropolitan University",
"Cardiff University",
"University of Chester",
"Coventry University",
"Cranfield University",
"University for the Creative Arts",
"University of Cumbria",
"De Montfort University",
"University of Derby",
"University of Dundee",
"Durham University",
"University of East Anglia",
"University of East London",
"Edge Hill University",
"University of Edinburgh",
"Edinburgh Napier University",
"University of Essex",
"University of Exeter",
"Falmouth University",
"University of Glasgow",
"Glasgow Caledonian University",
"University of Gloucestershire",
"University of Greenwich",
"Harper Adams University",
"Hartpury University",
"Heriot-Watt University",
"University of Hertfordshire",
"University of the Highlands and Islands",
"University of Huddersfield",
"University of Hull",
"Imperial College London",
"Keele University",
"University of Kent",
"Kingston University",
"University of Central Lancashire",
"Lancaster University",
"University of Leeds",
"Leeds Arts University",
"Leeds Beckett University",
"Leeds Trinity University",
"University of Leicester",
"University of Lincoln",
"University of Liverpool",
"Liverpool Hope University",
"Liverpool John Moores University",
"University of London",
"London Metropolitan University",
"London School of Economics",
"London South Bank University",
"Loughborough University",
"University of Manchester",
"Manchester Metropolitan University",
"Middlesex University",
"Newcastle University",
"Newman University",
"University of Northampton",
"Northeastern University – London",
"Northumbria University",
"Norwich University of the Arts",
"University of Nottingham",
"Nottingham Trent University",
"The Open University",
"University of Oxford",
"Oxford Brookes University",
"Plymouth Marjon University",
"Arts University Plymouth",
"University of Plymouth",
"University of Portsmouth",
"Queen Margaret University",
"Queen's University Belfast",
"Ravensbourne University",
"University of Reading",
"Regent's University London",
"Richmond American University London",
"Robert Gordon University",
"Roehampton University",
"Royal Agricultural University",
"Royal Holloway, University of London",
"University of Salford",
"University of Sheffield",
"Sheffield Hallam University",
"University of South Wales",
"University of Southampton",
"Solent University",
"University of St Andrews",
"St George's, University of London",
"St Mary's University, Twickenham",
"Staffordshire University",
"University of Stirling",
"University of Strathclyde",
"University of Suffolk",
"University of Sunderland",
"University of Surrey",
"University of Sussex",
"Swansea University",
"Teesside University",
"University of the Arts London",
"Ulster University",
"University of Law",
"University of Wales",
"University of Wales Trinity Saint David",
"University of Warwick",
"University of the West of England",
"University of the West of Scotland",
"University of West London",
"University of Westminster",
"University of Winchester",
"University of Wolverhampton",
"University of Worcester",
"Wrexham Glyndŵr University",
"University of York",
"York St John University",

];

export default universities;
